### ISSUE TITLE
Broken link for SecurityScheme

### ISSUE THREAD

**Issue by azan-n** [HiDeoo/starlight-openapi#20]
### Describe the bug

The link to the JWT security scheme is broken and leads nowhere.
<img width="699" alt="image" src="https://github.com/HiDeoo/starlight-openapi/assets/31279909/102ce17d-99c5-497b-8a0f-0e9b678795e2">

### To Reproduce

The schema used in the above image defines a SecurityScheme as

```json
"securitySchemes": {
      "JWT": {
        "type": "http",
        "description": "Utilize the Bearer token scheme with your access token included in the Authorization HTTP header.\n```Authorization: Bearer YOUR_ACCESS_TOKEN```",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
}
```

and the security field on the operation is defined as

```json
"security": [
          {
            "JWT": [
              "webhook:write"
            ]
          }
        ]
```

### Expected behavior

Ideally, a link to a page with the SecurityScheme definition would help here. If it makes things simpler, we can repeat all the information on all pages.

Happy to create a PR.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

The issue should now be fixed in [`v0.6.0`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.6.0).
