### ISSUE TITLE
Missing response schema

### ISSUE THREAD

**Issue by mdenson** [HiDeoo/starlight-openapi#29]
### Describe the bug

This project is great by the way. I can't seem to get the response schema (or anything other than the content picker) to show up in the response section. Same problem with the request section. It is a valid openapi 3.x file best I can tell (works on Swagger). Query and path parameters show up fine and use the same relative $ref links.

Here is response section of openapi file:
...
      responses:
        '200':
          description: Address book list results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListContactsResponse'
          headers: {}
...
Here is schema:
...
    ListContactsResponse:
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              contactName:
                type: string
              contactId:
                type: string
                example: amzn1.alexa.contacts.did.{id}
...

### To Reproduce

openapi file in /api just like example

### Expected behavior

should show schema or examples

### How often does this bug happen?

Every time

### System Info

Browser Chrome
starlight-openapi 0.6.2

**Comment by HiDeoo** [comment]
Thanks for your report.

Would you be able to provide the exact schema used when encountering the issue? Or share a repo that reproduces the issue?

**Comment by mdenson** [comment]
With latest version of starlight-openapi I am having the problem with this file (rename to .yaml)
[test.txt](https://github.com/HiDeoo/starlight-openapi/files/15018617/test.txt)

**Comment by HiDeoo** [comment]
Thanks, this really helped a lot.

This should be fixed in version [`0.6.3`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.6.3) that I just released.

For example, given the exact schema your shared, it now renders as expected:

![fix](https://github.com/HiDeoo/starlight-openapi/assets/494699/92be2da1-2fb8-484e-95a3-6f91379ee77c)

**Comment by mdenson** [comment]
fantastic! thank you
