### ISSUE TITLE
Run request

### ISSUE THREAD

**Issue by benjamin-Keller** [HiDeoo/starlight-openapi#32]
### Is your feature request related to a problem?

When going through API documentation, there is no way to run the API to see live data results

### Describe the solution you'd like

I'd like a button that says 'Run' next to the endpoint name or somewhere near the top of the page that will allow the user to run the request similar to SwaggerHub.

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

This kind of feature was part of the initial set of potential features for the plugin, but ended up not being implemented for various reasons:

- This is not something that I initially needed for my own use case
- I want to keep the client part of the plugin to be as simple and lightweight as possible
- I did not have the time to implement this feature

Today, these reasons are still valid and most likely will not change in the near future. However, I will be opened to discuss how such a feature could be implemented, how it would work or look in the plugin, if someone is willing to contribute to the project but that's a fairly large task. Altho, if this ends up being a feature, the default behavior will still be the same as it is today, and the user will have to opt-in to use this feature.
