### ISSUE TITLE
Fix README.md link

### ISSUE THREAD

**Issue by trueberryless** [HiDeoo/starlight-openapi#39]
### Describe the bug

The link to `Getting started guide` in README.md is wrong (`/guides`) is not necessary any more.

### To Reproduce

1. Go to README.md
2. click on `Getting started guide`

### Expected behavior

get me to vercel app

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report and taking the time to open an issue, super appreciated 🙌 

This is now fixed 🎉
