### ISSUE TITLE
anyOf support

### ISSUE THREAD

**Issue by dougsmith1000** [HiDeoo/starlight-openapi#4]
### Is your feature request related to a problem?

We love this library, but have an openapi spec that includes a lot of enums. 

### Describe the solution you'd like

Support enums

### Additional Context

What kind of gnarliness were you experiencing with [@readme/openapi-spe](https://github.com/readmeio/openapi-parser) ? It looks like that library isn't going to be updated any time soon. Maybe I could help dig through it if I find some extra time?

**Comment by HiDeoo** [comment]
Thanks for your feedback.

`anyOf` is supposed to be supported. You can check an example [here](https://starlight-openapi.vercel.app/api/v2/animals/operations/adddog/#request-body):

<img width="747" alt="image" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/ff2d1a45-329f-4188-846a-c16a1063ca2d">

If that is not the case for you, maybe this is a bug or a missing case. If so, could you provide a small schema/example which repro the issue?

**Comment by dougsmith1000** [comment]
It does! I'm sorry. I was misreading my spec. Apparently, it was allOf that I needed to work. My spec has the following property in it: 
![image](https://github.com/HiDeoo/starlight-openapi/assets/1891234/a1cf2166-54eb-46b0-8123-3ddc12bced95)
That points to this schema: 
![image](https://github.com/HiDeoo/starlight-openapi/assets/1891234/62bb5e1d-f8f7-41f7-8da3-0d3862e0e8e9)

However, the parser doesn't seem to understand the link. As a result, my rendered doc looks like 
![image](https://github.com/HiDeoo/starlight-openapi/assets/1891234/6794bd85-0a48-4699-9ee0-e28b15a87984)

**Comment by HiDeoo** [comment]
Ah I see the issue.

Thanks for providing the details 🙌  I'll setup a similar case and see how this can be fixed/improved.

**Comment by HiDeoo** [comment]
This should now be fixed in [`v0.2.1`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.2.1) which would display a similar setup like this:

<img width="661" alt="SCR-20231001-lswn" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/91a9e09f-e084-4dc0-a08f-c3b35f996884">

**Comment by dougsmith1000** [comment]
Looking good. Thank you!
