### ISSUE TITLE
Change look and feel of auto generated components

### ISSUE THREAD

**Issue by UserZer00** [HiDeoo/starlight-openapi#49]
### Is your feature request related to a problem?

I want to change the look and feel of the auto generated components that are based on the openapi specs. 

### Describe the solution you'd like

Is there a way of customizing the styling of the auto generated components?

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

Customization is definitely something I want to tackle in the future. I'm not sure yet which direction it'll take but I'm assuming it'll be something to address when getting closer to a v1.0.0 release.

In the meantime, a CSS based approach is probably the best way to go using Starlight [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/) (note that the experience will be improved when Starlight supports Cascade Layers which is currently [in the works](https://github.com/withastro/starlight/pull/2322)).
