### ISSUE TITLE
Support "anyOf" type

### ISSUE THREAD

**Issue by Pejman12** [HiDeoo/starlight-openapi#52]
### Describe the bug

Starlight openapi doesn't seem to support the `anyOf` type in openAPI 3.0 in the request schema (and maybe the response aswell).

### To Reproduce

have an anyOf in the openAPI definition, for example :
 ```json
 "anyOf": [
    {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      }
    }
  ]
```

### Expected behavior

Expected to handle the type.

### How often does this bug happen?

Every time

### System Info

all systems.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

I think I may need a small reproducible example to understand the issue in this case as it looks like I'm not able to reproduce it.

For example, given the following definition which uses `anyOf`:

```yml
paths:
  /pets:
    post:
      description: Creates a new pet in the store. Duplicates are allowed
      operationId: addPet
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: 'object'
                  properties:
                    foo:
                      type: 'string'
                - type: 'object'
                  properties:
                    bar:
                      type: 'string'
```

It renders as expected for me:

<img width="747" alt="image" src="https://github.com/user-attachments/assets/ad1b1ba4-1a8c-41d4-b5de-d8c43778e348">

**Comment by Pejman12** [comment]
thx a lot for ur reactivity 👏🏼
